export const dashboardData = {
  activeServices: [
    {
      service_id: "PR-201",
      service_name: "Passport",
      category: "travel",
      expiry_date: "2026-01-25",
      document_number: "P987654321",
      status: "valid",
      days_left: 28,
    },
    {
      service_id: "DL-101",
      service_name: "Driver License",
      category: "vehicle",
      expiry_date: "2026-03-14",
      license_type: "Private",
      status: "valid",
      days_left: 72,
    },
    {
      service_id: "ID-001",
      service_name: "National ID",
      category: "identity",
      expiry_date: "2026-06-09",
      status: "valid",
      days_left: 150,
    },
  ],
  pastTravels: [
    {
      travel_id: "T-2024-001",
      destination_country: "United Arab Emirates",
      city: "Dubai",
      travel_purpose: "Leisure",
      entry_date: "2024-08-12",
      exit_date: "2024-08-18",
      travel_duration_days: 6,
      travel_method: "Air",
      airline: "Flynas",
    },
    {
      travel_id: "T-2023-014",
      destination_country: "Turkey",
      city: "Istanbul",
      travel_purpose: "Vacation",
      entry_date: "2023-06-05",
      exit_date: "2023-06-14",
      travel_duration_days: 9,
      travel_method: "Air",
      airline: "Turkish Airlines",
    },
    {
      travel_id: "T-2022-009",
      destination_country: "United Kingdom",
      city: "London",
      travel_purpose: "Study / Training",
      entry_date: "2022-11-20",
      exit_date: "2022-12-05",
      travel_duration_days: 15,
      travel_method: "Air",
      airline: "Saudi Airlines",
    },
  ],
  violations: [{ violation_id: "V-71129", type: "Speeding", amount: 300, date: "2024-12-10", status: "unpaid" }],
};
